%YAML:1.0

# gpio info
gpio.button_startstop: 
    pin_id: 249
    longthresh: 2000

#zed info
zed:
    fps: 30
    resolution: RESOLUTION_VGA
    compression: COMPRESSION_HEVC

#arduino info
arduino:
    port: /dev/ttyACM0
    speed: 3

